WHO = read.csv("WHO.csv")
str(WHO)
summary(WHO)
mean(WHO$Under15)
 sd(WHO$Under15)
summary(WHO$Under15)
 which.min(WHO$Under15)
WHO$Country[86]
plot(WHO$GNI, WHO$FertilityRate)
Outliers = subset(WHO, GNI>10000 & FertilityRate > 2.5)
 nrow(Outliers)
hist(WHO$CellularSubscribers)
 boxplot(WHO$LifeExpectancy ~ WHO$Region)

table(WHO$Region)
tapply(WHO$Over60,WHO$Region, mean)
tapply(WHO$LiteracyRate,WHO$Region, min,na.rm=TRUE)

USDA = read.csv("USDA.csv")
str(USDA)
summary(USDA)
names(USDA)
 USDA$Description[which.max(USDA$Sodium)]
 HighSodium = subset(USDA, Sodium>10000)
 nrow(HighSodium)
HighSodium$Description
match("CAVIAR", USDA$Description)
USDA$Sodium[4154]
summary(USDA$Sodium)
sd(USDA$Sodium, na.rm=TRUE)
plot(USDA$Protein, USDA$TotalFat)
hist(USDA$VitaminC, xlim=c(0,100), breaks=2000)
boxplot(USDA$Sugar)
USDA$HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium,na.rm=TRUE))
USDA$HighProtein = as.numeric(USDA$Protein > mean(USDA$Protein,na.rm=TRUE))
USDA$HighCarb = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate,na.rm=TRUE))
USDA$HighFat = as.numeric(USDA$TotalFat> mean(USDA$TotalFat,na.rm=TRUE))
table(USDA$HighSodium)
table(USDA$HighSodium,USDA$HighFat)
tapply(USDA$Iron,USDA$HighProtein,mean,na.rm=TRUE)
tapply(USDA$VitaminC,USDA$HighCarb,max,na.rm=TRUE)
 tapply(USDA$VitaminC,USDA$HighCarb,summary,na.rm=TRUE)